[theme]
primaryColor = "#D20A0A"
backgroundColor = "#F1F5F9"          # Fond global du site (Gris clair net)
secondaryBackgroundColor = "#FFFFFF" # Fond natif des conteneurs/bulles st.container() (Blanc pur)
textColor = "#0F172A"                # Couleur du texte (Noir/Slate très sombre)
font = "sans serif"

[server]
headless = true
