[theme]
primaryColor = "#3D3EEA"
backgroundColor = "#F1F5F9"          # Fond global du site (Gris clair net)
secondaryBackgroundColor = "#FFFFFF" # Fond natif des conteneurs/bulles st.container() (Blanc pur)
textColor = "#1E293B"                # Couleur du texte (Gris foncé)
font = "sans serif"

[server]
headless = true
